# Global and/or per-project file to override default configuration
config_filename: my_config.yaml # Default

# Path to the project (relative to `main.py`)
projects_dir: my_projects # Default
project_name: demo # Default

# Names of working directories (inside the project directory)
input_dirname: input # Default
templates_dirname: null # Default
output_dirname: output # Default

# Optional YAML files in the project directory (and deeper) to update variables
vars_filename: vars.yaml # Default

# Extensions
output_ext: .txt # Default

# Name of variable to derive from target YAML filename (if not already set)
# filename_variable: hostname # File `GW01.yaml` will result in {hostname: GW01}
# filename_variable: person.name # `Alex.yaml` -> {person: {name: Alex}}
filename_variable: null # Default

# Additional subdirectory for the final template
template_subdir: . # Default: No additional subdirectory

# Template name without ".j2" extension
template_name: base # Default

# Set to a string (e.g. "skip_") to skip YAMLs/dirs with this prefix. Does not
# apply to the working directories
skip_prefix: null # Default

# Whether to save final (fully merged) YAML files
save_merged_yamls: false # Default

# In case `save_merged_yamls` is `true`:
# Optional root directory for saving final (merged) YAML files.  If set to None,
# YAML files will be saved in a "yamls" subdirectory in `output_data_dir`
# directory where rendered output files are saved (e.g., _output_data/yamls/)
# Examples:
#   merged_yamls_path: null
#     _input_data/cisco_ios/router/my-device.yaml ->
#     _output_data/yamls/cisco_ios/router/my-device.yaml
#   merged_yamls_path: merged_yamls
#     _input_data/cisco_ios/router/my-device.yaml ->
#     merged_yamls/cisco_ios/router/my-device.yaml
merged_yamls_path: null # Default

# https://docs.python.org/3/library/logging.html#logging.basicConfig
log_level: 30 # 30 - warning (default), 20 - info, 10 - debug

log_style: "{" # Default

log_format: "[{asctime}] {levelname:<8} {message}" # Default
# log_format: "{message}" # Better for debugging

log_datefmt: "%Y-%m-%d %H:%M:%S" # Default
